# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-23 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personID', models.IntegerField()),
                ('firstName', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=250)),
                ('employerID', models.IntegerField(max_length=250)),
                ('nidaID', models.CharField(max_length=250)),
                ('passportNumber', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testingID', models.IntegerField()),
                ('superceededDate', models.DateField()),
                ('negativeResult', models.IntegerField()),
                ('activeFlag', models.IntegerField()),
                ('createdDtime', models.DateField()),
                ('certificateID', models.IntegerField()),
                ('personID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Person')),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='testingID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Test'),
        ),
    ]
