# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-23 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employerName', models.CharField(max_length=300)),
                ('employerEmail', models.CharField(max_length=300)),
            ],
        ),
    ]
