# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-24 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_employer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordDate', models.DateField()),
                ('unitID', models.IntegerField()),
                ('client', models.CharField(max_length=300)),
                ('clientEmail', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=300)),
                ('event', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=300)),
                ('startDate', models.DateField()),
            ],
        ),
    ]
