# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-24 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200524_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passportNumber',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
